export enum GameActions {
  DISCARD_DITCH_GAME_REQUEST = "DISCARD_DITCH_GAME_REQUEST",
  SHOW_DITCH_GAME_REQUEST = "SHOW_DITCH_GAME_REQUEST",
  SELECT_BATTLESHIP = "SELECT_BATTLESHIP",
  CHANGE_DIRECTION = "CHANGE_DIRECTION",
  GET_HIGHLIGHTED_INDEXES = "GET_HIGHLIGHTED_INDEXES",
  REMOVE_HIGHLIGHTED = "REMOVE_HIGHLIGHTED",
  PLACE_BATTLESHIP_ON_BOARD = "PLACE_BATTLESHIP_ON_BOARD",
  RESET_GAME_STATE = "RESET_GAME_STATE",
  SYNCHRONIZE_GAME_STATE_WITH_SERVER = "SYNCHRONIZE_GAME_STATE_WITH_SERVER",
}
